name: Generate GitHub Trophies

on:
  workflow_dispatch:

jobs:
  trophy:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate trophy
        uses: Erik-Donath/github-profile-trophy@feature/generate-svg
        with:
          username: manoj-hg
          output_path: trophy.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit trophy
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Generate GitHub trophies"
          file_pattern: trophy.svg
